### ISSUE TITLE
[ACE] (frag) fza_30x113 rpt spam

### ISSUE THREAD

**Issue by blindbat2006** [SachaOropeza/AH64D-v1.43-#21]
This problem is only for people who use ace3.

22:12:45 [ACE] (frag) INFO: Ammo class fza_30x113 lacks proper explosive properties definitions for frag!
22:12:45 [ACE] (frag) INFO: Ammo class fza_30x113 lacks proper explosive properties definitions for frag!
22:12:45 [ACE] (frag) INFO: Ammo class fza_30x113 lacks proper explosive properties definitions for frag!
22:12:45 [ACE] (frag) INFO: Ammo class fza_30x113 lacks proper explosive properties definitions for frag!

My fix would be @ line 702 (class B_30mm_MP: BulletBase) of config.cpp between the {}; put in ace_frag_skip = 1; this would hopefully stop all the rpt spam from any of the weapons and will skip ace fragmentation framework altogether. 

Link to ace frag framework https://ace3mod.com/wiki/framework/frag-framework.html

**Comment by SachaOropeza** [comment]
Have you fixed it ?

**Comment by blindbat2006** [comment]
Yes the fix above has stop the rpt spamming for fza_30x113 and 1 or 2 of the missiles but not all as off yet.

**Comment by blindbat2006** [comment]
Fix
https://github.com/SachaOropeza/AH64D-v1.43-/commit/ceb8c533a6e1a94f85213608a6845ae96aea0024
